//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBanHangLaptop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Laptop
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Laptop()
        {
            this.ChiTietDonHangs = new HashSet<ChiTietDonHang>();
        }
    
        public int MaLaptop { get; set; }
        public string TenLaptop { get; set; }
        public Nullable<double> GiaBan { get; set; }
        public Nullable<double> GiaGoc { get; set; }
        public string MoTa { get; set; }
        public Nullable<System.DateTime> NgayCapNhat { get; set; }
        public string AnhBia { get; set; }
        public Nullable<int> SoLuongTon { get; set; }
        public Nullable<int> MaNCC { get; set; }
        public Nullable<int> Moi { get; set; }
        public Nullable<int> MaLoai { get; set; }
        public string ChiTietLaptop { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietDonHang> ChiTietDonHangs { get; set; }
        public virtual LoaiLaptop LoaiLaptop { get; set; }
        public virtual NhaCungCap NhaCungCap { get; set; }
    }
}
